# Generated by Django 4.1.4 on 2023-03-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='tags',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
